name: Build News Feed

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch: {}       # allow manual run
  push:
    paths:
      - "scripts/fetch-news.mjs"
      - "package.json"
      - ".github/workflows/news.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

- name: Setup Node (with npm cache)
  uses: actions/setup-node@v4
  with:
    node-version: '20'
    cache: 'npm'

- name: Install dependencies
  run: |
    if [ -f package-lock.json ]; then
      npm ci --no-audit --fund=false
    else
      npm i --no-audit --fund=false
    fi


      - name: Build feed
        run: npm run build:news

- name: Commit changes (if any)
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    git add -A
    if git diff --cached --quiet; then
      echo "No changes to commit."
    else
      git commit -m "Update news feed [skip ci]"
      git push
    fi


